import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/shared/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Connected",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute={'class'}
            defaultTheme="system"
            enableSystem
          >
        <ConvexClientProvider>
          <NavBar />
            <div className="p-1">
              {children}
            </div>
          
        </ConvexClientProvider>
        </ThemeProvider>
        </body>
    </html>
  );
}
